# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: coding人生
subtitle: keep coding
description:
author: laien.liang
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://laienliang.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

fancybox: true ## If you want to use fancybox please set the value to true
google_search: true ## Use Google search, true/false
baidu_search: true ## Use Baidu search, true/false
# swiftype: ## Your swiftype_key, e.g. m7b11ZrsT8Me7gzApciT
# tinysou: ## Your tinysou_key, e.g. 4ac092ad8d749fdc6293
# google_analytics: ## Your Google Analytics tracking id, e.g. UA-42425684-2
# baidu_analytics: ## Your Baidu Analytics tracking id, e.g. 8006843039519956000

menu:
  page: home
  directory: .
  icon: icon-home
  page: archive
  directory: archives/
  icon: icon-archive
  page: about
  directory: about/
  icon: icon-about
  page: rss
  directory: atom.xml
  icon: icon-rss



links:
  title: site-name1
  url: http://www.example1.com/
  title: site-name2
  url: http://www.example2.com/
  title: site-name3
  url: http://www.example3.com/

# Static files
js: js
css: css

highlight:
  enable: true
  auto_detect: true
  line_number: true
  tab_replace:

# Theme version
version: 0.0.0

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: maupassant

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
      github: git@github.com:laienliang/laienliang.github.com.git,master
